export const TOWERS = [
  {
    id: "pebble",
    name: "Pebble",
    shape: "circle",
    color: "#78bf70",
    cost: 2,
    role: "shooter",
    damage: 12,
    rate: 0.55,
    range: 2,
    hp: 40,
    description:
      "Rapid shots for scouts and speedy visitors. Short range; armor resists its pebbles.",
    tag: "Rapid fire",
  },
  {
    id: "prism",
    name: "Prism",
    shape: "triangle",
    color: "#e8b450",
    cost: 3,
    role: "piercing",
    damage: 42,
    rate: 2.7,
    range: 7,
    hp: 65,
    description:
      "A long-range beam that ignores armor. Powerful against tanks, slow against a crowd.",
    tag: "Armor breaker",
  },
  {
    id: "bricky",
    name: "Bricky",
    shape: "square",
    color: "#e89583",
    cost: 2,
    role: "block",
    damage: 5,
    rate: 1,
    range: 0,
    hp: 240,
    description:
      "Stops visitors, bonks back, and reflects some damage. Keeps enemies in your shooters’ range.",
    tag: "Block & reflect",
  },
  {
    id: "frost",
    name: "Frost",
    shape: "diamond",
    color: "#79c8db",
    cost: 3,
    role: "slow",
    damage: 2,
    rate: 2,
    range: 3.5,
    hp: 65,
    description:
      "A gentle chill slows nearby visitors across three lanes. Pair with a damage dealer.",
    tag: "Area slow",
  },
  {
    id: "poppy",
    name: "Poppy",
    shape: "pentagon",
    color: "#b09ad9",
    cost: 4,
    role: "splash",
    damage: 25,
    rate: 2.4,
    range: 4.75,
    hp: 60,
    description:
      "A bubbly blast hits a whole group, including the next lane. Best against tiny swarms.",
    tag: "Swarm popper",
  },
];

export const ENEMIES = {
  scout: {
    name: "Scout",
    hp: 32,
    speed: 0.24,
    armor: 0,
    attack: 8,
    counter: "Pebble",
  },
  skater: {
    name: "Skater",
    hp: 25,
    speed: 0.43,
    armor: 0,
    attack: 8,
    counter: "Pebble + Frost",
  },
  swarm: {
    name: "Swarm",
    hp: 16,
    speed: 0.3,
    armor: 0,
    attack: 8,
    counter: "Poppy + Frost",
  },
  tank: {
    name: "Armored visitor",
    hp: 170,
    speed: 0.17,
    armor: 0.7,
    attack: 14,
    counter: "Prism or Bricky + Pebble",
  },
  boss: {
    name: "Captain",
    hp: 260,
    speed: 0.14,
    armor: 0.7,
    attack: 18,
    counter: "Prism or a protected firing line",
  },
};

export const MISSIONS = [
  {
    id: "first-contact",
    title: "First contact",
    subtitle: "A little math. A big adventure.",
    skill: "addition",
    difficulty: 1,
    world: "Earth orbit",
    label: "Addition",
    waveCount: 3,
  },
  {
    id: "moon-mail",
    title: "Moon mail",
    subtitle: "Special delivery from outer space.",
    skill: "subtraction",
    difficulty: 2,
    world: "Moon meadow",
    label: "Subtraction",
    waveCount: 3,
  },
  {
    id: "ring-road",
    title: "The ring road",
    subtitle: "Double the trouble, double the teamwork.",
    skill: "multiplication",
    difficulty: 3,
    world: "Saturn express",
    label: "Multiplication",
    waveCount: 3,
  },
  {
    id: "sharing-space",
    title: "Sharing space",
    subtitle: "There’s room in the galaxy for everyone.",
    skill: "division",
    difficulty: 4,
    world: "Starlight station",
    label: "Division",
    waveCount: 3,
  },
  {
    id: "cosmic-mix",
    title: "Cosmic mix",
    subtitle: "Bring everything you’ve learned.",
    skill: "mixed",
    difficulty: 5,
    world: "Nebula garden",
    label: "Mixed practice",
    waveCount: 3,
  },
  {
    id: "home-sweet-earth",
    title: "Home, sweet Earth",
    subtitle: "Your little planet is counting on you.",
    skill: "mixed",
    difficulty: 6,
    world: "Earth homecoming",
    label: "Mixed practice",
    waveCount: 3,
  },
];
export const SKILLS = [
  {
    id: "addition",
    name: "Addition",
    symbol: "+",
    color: "#75b866",
    description: "Put small numbers together.",
  },
  {
    id: "subtraction",
    name: "Subtraction",
    symbol: "−",
    color: "#75bad5",
    description: "Find what’s left over.",
  },
  {
    id: "multiplication",
    name: "Multiplication",
    symbol: "×",
    color: "#b49bd8",
    description: "Discover equal groups.",
  },
  {
    id: "division",
    name: "Division",
    symbol: "÷",
    color: "#e9b967",
    description: "Share into equal groups.",
  },
];
export const COSMETICS = [
  {
    id: "classic",
    name: "Earth original",
    description: "Home looks good on you.",
    cost: 0,
    color: "#72bf8c",
  },
  {
    id: "lilac",
    name: "Lilac skies",
    description: "A dreamy coat of cosmic purple.",
    cost: 4,
    color: "#b59de1",
  },
  {
    id: "sunset",
    name: "Peachy planet",
    description: "A little golden-hour glow.",
    cost: 6,
    color: "#efa889",
  },
  {
    id: "ocean",
    name: "Ocean explorer",
    description: "For a wonderfully blue world.",
    cost: 8,
    color: "#72bcd6",
  },
];
